# Generated by Django 4.1.7 on 2023-04-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_uploadedfile_project_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criteria',
            field=models.TextField(null=True),
        ),
    ]
